mutation InsertUser @auth(level: USER) {
  user_insert(data: {
    displayName: "Test User",
    email: "test@example.com",
    createdAt_expr: "request.time"
  })
}

query ListDocuments @auth(level: USER) {
  documents {
    id
    filename
    fileType
    uploadDate
  }
}

mutation UpdateDocumentDescription($documentId: UUID!, $description: String!) @auth(level: USER) {
  document_update(
    key: { id: $documentId },
    data: { description: $description }
  )
}

query ListFoldersForUser @auth(level: USER) {
  folders(where: { userId_expr: "auth.uid" }) {
    id
    name
    description
    createdAt
  }
}