type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  organization: String
}

type Document @table {
  filename: String!
  fileType: String!
  uploadDate: Timestamp!
  url: String!
  description: String
  tags: [String]
  user: User
}

type AnalysisTask @table {
  analysisType: String!
  status: String!
  requestedAt: Timestamp!
  completedAt: Timestamp
  errorDetails: String
  document: Document
}

type AnalysisResult @table {
  resultData: String!
  createdAt: Timestamp!
  summary: String
  keywords: [String]
  sentiment: String
  analysisTask: AnalysisTask
}

type Folder @table {
  name: String!
  createdAt: Timestamp!
  description: String
  parentFolderId: UUID
  user: User
}

type DocumentFolder @table(key: ["document", "folder"]) {
  assignedAt: Timestamp!
  document: Document!
  folder: Folder!
}